# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
reviews:
  profile: "assertive"
  high_level_summary: true
  poem: false

  # Filter out noise to keep the review focused on your logic
  path_filters:
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/build/**"
    - "!package-lock.json"
    - "!yarn.lock"
    - "!pnpm-lock.yaml"
    - "!**/*.{png,jpg,jpeg,gif,svg,ico}" # Ignore assets
    - "src/**/*.{ts,tsx}"                 # Focus on source TS/TSX files

  path_instructions:
    - path: "src/**/*.{ts,tsx}"
      instructions: |
        You are a Senior Frontend Engineer reviewing a React TypeScript application built with Vite.
        Please focus your review on:
        1. **TypeScript Best Practices**: Ensure proper interface/type definitions and avoid 'any' types.
        2. **React Hooks**: Check for proper dependency arrays in useEffect/useMemo and ensure hooks aren't called conditionally.
        3. **Performance**: Look for unnecessary re-renders or expensive computations that should be memoized.
        4. **Vite/Modern ESM**: Suggest modern web APIs and ESM-compatible patterns.
        5. **Clean Code**: Ensure components are modular and props are handled efficiently.

chat:
  auto_reply: true # Allows you to have a back-and-forth discussion on the PR